server:
  port: 7002

spring:
  application:
    name: config-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hongmingqiu/configDemo
          username: 674057313@qq.com  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: zxc13631146676
          basedir: ../config/basedir

eureka:
  client:
    service-url:
      defaultZone: http://172.20.14.118:8778/eureka/
     
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
    bus-refresh:
      enabled: true
    



