server:
port: 8200

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


spring:
  profiles:
    active: dev  #**部署运行环境，dev:开发，test:测试，produce:生产
  application:
    name: sscp-passenger
  redis:  #redis配置
    database: 0
    host: 47.244.5.51
    port: 6379
    password:
    timeout: 20000
    #cluster:
      #nodes: 192.168.211.134:7000,192.168.211.134:7001
      #max-redirects:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@47.244.5.51:1521:xe
    username: passengerdb
    password: pcidata_2019
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 10    # 初始化连接数
#      min-idle: 10        # 最小空闲连接
#      max-active: 100     # 最大活动链接
#      max-wait: 60000     # 最大等待时间(毫秒)
#      test-while-idle: true
#      test-on-borrow: false # 获取连接时测试是否可用
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      min-evictable-idle-time-millis: 300000
#      filter:
#        slf4j:
#          enabled: true
#      proxyFilters:
#        - com.mtr.sscp.filter.SqlLogFilter
    initial-size: 10    # 初始化连接数
    min-idle: 10        # 最小空闲连接
    max-active: 100     # 最大活动链接
    max-wait: 60000     # 最大等待时间(毫秒)
    test-while-idle: true
    test-on-borrow: false # 获取连接时测试是否可用
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    min-evictable-idle-time-millis: 300000
  session:
    store-type: redis
  resources:
    static-locations: ["/static/"]
  jackson:
    date-format: dd/MM/yy HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      #热部署生效
      enabled: false

mybatis:
  type-aliases-package: com.mtr.sscp.entity
  mapper-locations: classpath:mapper/*.xml
#  驼峰命名规范，不加不能把tap_time映射为tapTime字段实体
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

#logback:
#  #非开发环境是否开启控制台日志
#  enableConsoleLogWhenNotInDev: false
#  #**日志文件存放目录，目录后面无需再加"/"。备注如果这项不配置，则不输出日志文件
#  logFileDir: /fs01/log


#jdbc操作日志
log:
  jdbc:
    ps:
      executableSql: true
    rs:
      header: true

# /swagger-ui.html swagger访问网址
swagger:
  enable: true

#分布式id机器码      
snowflake:
  workerId: 0  #取值0-31
  datacenterId: 1  #取值0-31

parameters:
  mtrAuthorizationUrl: www.baidu.com 	#Mtr授权Url
